### PR TITLE
WIP: Resolution recommendations

### PR DESCRIPTION
**Pull request by Yukitty**
I changed up the resolutions table to include literally every resolution I could shoehorn into it, display aspect ratios, and even mark "recommended resolutions" (multiples of 320x240 with no funny business) with the key item dots. I even managed to get 800x600 "working", although it's a bit of a stretch.

But, considering handling weird aspect ratios is largely a messy work in progress effort still... 🤔 It'd prooobably be better to go in completely the other direction and _disable_ most of the deviant window resolutions outside of debug builds instead, right? Hum.

Marked WIP because I _don't_ really recommend merging it. At least not at this time. I also reordered the resolutions in the process, so it'd break existing settings.dat

### CODE REVIEW

**Comment by Yukitty** [comment]
I really like the widescreen multiples of 384x240 (16:10), to be honest. And 1280x720, since it's the only clean multiple of 426.66666666...x240 for 16:9 aspect ratio.

The point is, those particular resolutions are based on clean multiples of the screen height, 240, so they are _truely_ only "widescreen" and don't also add holes to the top and bottom of every length-oriented map.

**Comment by isage** [comment]
Ugh. First of all, this breaks existing setting.dat, so settings version needs to be bumped up.
Second, most of those new resolutions won't work fullscreen. Depending on OS/Graphics drivers this will lead to inability to select correct resolution while fullscreen.
Reason behind original list of resolutions is cleanly supporting most of desktop fullscreen resolutions.
There's not that much 16:10 monitors around.

**Comment by Yukitty** [comment]
I know.
But I also don't like the fullscreen resolution changing immediately every time I press left or right, either.
Maybe I'll make a sub-menu for selecting a resolution, or disable resolutions in fullscreen mode based on what your monitor actually supports. I know mine certainly doesn't support _either_ of the 136X resolutions.

**Comment by isage** [comment]
I'll close this, but maybe i'll add some of mentioned resolutions later.

**Pull request closed without merging**
