### PR TITLE
Nikumaru Title BGs

### PR DESCRIPTION
**Pull request by Yukitty**
This is just something I did for myself that I'm willing to share. It's alright if you'd rather not take it.

I changed the title screen state to not load a map at all (normally it loads `Stage/0.pxm` and whatnot)
and instead pick a background along with the current Nikumaru Counter title screen character and music.

I also added a new backdrop scrolling type for this purpose, which makes every backdrop scroll smoothly along to the left at a leisurely pace, not just clouds.

Here are preview screenshots of my background selections for each character:
screenshot
title-curly
screenshot-toroko
screenshot-king
screenshot-sue

### CODE REVIEW

**Comment by isage** [comment]
Aesthetically, i like moon BG better.
Can we make this at least build-time configurable?

**Comment by Yukitty** [comment]
Mmm. That might not be too difficult, I think. I did make a special case in the code that makes bkMoon and bkFog move the way they're supposed to, there just needs to be something that sets the backdrop to bkMoon.

**Comment by Yukitty** [comment]
Done. :3
CMake will let you toggle the define for it easily, just "configure" again to update the list of options.

**Comment by isage** [comment]
In the end, i've decided to mix both: i've created additional cloud-scrolling-type backgrounds for each nikumaru "stage"

**Pull request closed without merging**
