### PR TITLE
Organya improvements

### PR DESCRIPTION
**Pull request by alula**
- Makes the drum samples match Cave Story (the current implementation handles them like old versions of OrgMaker do, which makes some songs, notably Gestation and Credits theme sound a bit weird)
- Makes panning work more or less like OrgMaker.
- Adds cubic interpolation mode (maybe then add an in-game or a compile-time selector?).

### CODE REVIEW

**Comment by isage** [comment]
Yeah, can you add compile-time selector for interpolation for now? Last time we implemented interpolation it crippled console ports (and some pc's somehow)

**Comment by alula** [comment]
done

**Comment by isage** [comment]
> done
Should be off by default, though

**Comment by alula** [comment]
why is LOW_END_HARDWARE enabled by default tho?

**Comment by isage** [comment]
> why is LOW_END_HARDWARE enabled by default tho?

Hmm. I should remove that.
Anyway, it's because of the problems with interpolation on some PC's and consoles

**Comment by isage** [comment]
See #173

**Comment by isage** [comment]
Anyway, I'll make it runtime option, but for now it should be disabled by default

**Comment by alula** [comment]
I don't think that cubic/linear interpolation is that CPU heavy compared to Lanczos that was present in code before?

**Comment by isage** [comment]
I guess, but still needs checking first on all platforms.

**Comment by isage** [comment]
Thanks!

**Comment by isage** [comment]
Shit, i misread what cmake option does (need my morning coffee).
Fixed, though.

**Pull request merged**
